# Generated by Django 4.1.2 on 2024-06-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id_propiedad', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('valor_venta', models.IntegerField(max_length=10)),
                ('valor_arriendo', models.IntegerField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo_propiedad', models.CharField(max_length=20)),
            ],
        ),
    ]
